

### Suman runner start ###

Beginning of run at 1477418685473 = [Tue Oct 25 2016 11:04:45 GMT-0700 (PDT)]
Command issued from the following directory "/Users/t_millal/WebstormProjects/oresoftware/suman"
Command = ["/Users/t_millal/.nvm/versions/node/v6.7.0/bin/node","/Users/t_millal/.nvm/versions/node/v6.7.0/bin/suman","test/integration-tests/"]


[test3.js] 
[test3.js] 
[test3.js]  ### Suman end run ### 
[test3.js] 
[test3.js] 
[test3.js] 
[test3.js] 

[test2.js]  => Suman non-fatal error => Error in hook and "fatal" option for the hook is set to false => 
[test2.js] 	TypeError: Cannot assign to read only property 'done' of function 'function done(err) {
[test2.js] 	                        if (!t.callbackMode) {
[test2.js] 	                            handleNonCallba...<omitted>... }'
[test2.js] 	    at TestSuiteBase.<anonymous> (/Users/t_millal/WebstormProjects/oresoftware/suman/test-target/integration-tests/test2.js:21:24)
[test2.js] 	    at /Users/t_millal/WebstormProjects/oresoftware/suman/lib/test-suite-helpers/make-handle-befores-afters.js:157:43
[test2.js] 	    at _combinedTickCallback (internal/process/next_tick.js:67:7)
[test2.js] 	    at process._tickDomainCallback (internal/process/next_tick.js:122:9)

[test2.js] 
[test2.js] 
[test2.js] Test error: does 1
[test2.js] 	stack: Error: blind
[test2.js]     at TestSuiteBase.<anonymous> (/Users/t_millal/WebstormProjects/oresoftware/suman/test-target/integration-tests/test2.js:26:23)
[test2.js]     at /Users/t_millal/WebstormProjects/oresoftware/suman/lib/test-suite-helpers/handle-test.js:197:56
[test2.js]     at _combinedTickCallback (internal/process/next_tick.js:67:7)
[test2.js]     at Immediate._tickDomainCallback (internal/process/next_tick.js:122:9)
[test2.js]     at tryOnImmediate (timers.js:554:5)
[test2.js]     at processImmediate [as _immediateCallback] (timers.js:533:5)
[test2.js] 
[test2.js] 

[test2.js] 
[test2.js] 
[test2.js]  ### Suman end run ### 
[test2.js] 
[test2.js] 
[test2.js] 
[test2.js] 

[test1.js] 
[test1.js] 
[test1.js]  ### Suman end run ### 
[test1.js] 
[test1.js] 
[test1.js] 
[test1.js] 

[test7.js] 
[test7.js] 
[test7.js] Test error: oodles
[test7.js] 	stack: AssertionError: false == true
[test7.js]     at TestSuiteBase.<anonymous> (/Users/t_millal/WebstormProjects/oresoftware/suman/test-target/integration-tests/test7.js:30:9)
[test7.js]     at /Users/t_millal/WebstormProjects/oresoftware/suman/lib/test-suite-helpers/handle-test.js:197:56
[test7.js]     at _combinedTickCallback (internal/process/next_tick.js:67:7)
[test7.js]     at process._tickDomainCallback (internal/process/next_tick.js:122:9)
[test7.js] 
[test7.js] 

[test7.js] 
[test7.js] 
[test7.js] Test error: oodles
[test7.js] 	stack: AssertionError: false == true
[test7.js]     at TestSuiteBase.<anonymous> (/Users/t_millal/WebstormProjects/oresoftware/suman/test-target/integration-tests/test7.js:34:9)
[test7.js]     at /Users/t_millal/WebstormProjects/oresoftware/suman/lib/test-suite-helpers/handle-test.js:197:56
[test7.js]     at _combinedTickCallback (internal/process/next_tick.js:67:7)
[test7.js]     at Immediate._tickDomainCallback (internal/process/next_tick.js:122:9)
[test7.js]     at tryOnImmediate (timers.js:554:5)
[test7.js]     at processImmediate [as _immediateCallback] (timers.js:533:5)
[test7.js] 
[test7.js] 

[test7.js] 
[test7.js] 
[test7.js]  ### Suman end run ### 
[test7.js] 
[test7.js] 
[test7.js] 
[test7.js] 

[test8.js] 
[test8.js] 
[test8.js] Test error: oodles
[test8.js] 	stack: AssertionError: false == true
[test8.js]     at TestSuiteBase.<anonymous> (/Users/t_millal/WebstormProjects/oresoftware/suman/test-target/integration-tests/test8.js:29:9)
[test8.js]     at /Users/t_millal/WebstormProjects/oresoftware/suman/lib/test-suite-helpers/handle-test.js:197:56
[test8.js]     at _combinedTickCallback (internal/process/next_tick.js:67:7)
[test8.js]     at process._tickDomainCallback (internal/process/next_tick.js:122:9)
[test8.js] 
[test8.js] 

[test8.js] 
[test8.js] 
[test8.js] Test error: oodles
[test8.js] 	stack: AssertionError: false == true
[test8.js]     at TestSuiteBase.<anonymous> (/Users/t_millal/WebstormProjects/oresoftware/suman/test-target/integration-tests/test8.js:33:9)
[test8.js]     at /Users/t_millal/WebstormProjects/oresoftware/suman/lib/test-suite-helpers/handle-test.js:197:56
[test8.js]     at _combinedTickCallback (internal/process/next_tick.js:67:7)
[test8.js]     at Immediate._tickDomainCallback (internal/process/next_tick.js:122:9)
[test8.js]     at tryOnImmediate (timers.js:554:5)
[test8.js]     at processImmediate [as _immediateCallback] (timers.js:533:5)
[test8.js] 
[test8.js] 

[test8.js] 
[test8.js] 
[test8.js]  ### Suman end run ### 
[test8.js] 
[test8.js] 
[test8.js] 
[test8.js] 

[test4.js] 
[test4.js] 
[test4.js]  ### Suman end run ### 
[test4.js] 
[test4.js] 
[test4.js] 
[test4.js] 

[test5.js] 
[test5.js] 
[test5.js]  ### Suman end run ### 
[test5.js] 
[test5.js] 
[test5.js] 
[test5.js] 

[test0.js] TypeError: "callback" argument must be a function
[test0.js]     at exports.setTimeout (timers.js:322:11)
[test0.js]     at TestSuiteBase.<anonymous> (/Users/t_millal/WebstormProjects/oresoftware/suman/test-target/integration-tests/test0.js:172:13)
[test0.js]     at /Users/t_millal/WebstormProjects/oresoftware/suman/lib/test-suite-helpers/handle-test.js:189:37
[test0.js]     at _combinedTickCallback (internal/process/next_tick.js:67:7)
[test0.js]     at process._tickDomainCallback (internal/process/next_tick.js:122:9)

[test0.js] Warning: the following test callback was invoked twice by your code for the following test/hook => aaa1

[test0.js] TypeError: "callback" argument must be a function
[test0.js]     at exports.setTimeout (timers.js:322:11)
[test0.js]     at TestSuiteBase.<anonymous> (/Users/t_millal/WebstormProjects/oresoftware/suman/test-target/integration-tests/test0.js:178:13)
[test0.js]     at /Users/t_millal/WebstormProjects/oresoftware/suman/lib/test-suite-helpers/handle-test.js:189:37
[test0.js]     at _combinedTickCallback (internal/process/next_tick.js:67:7)
[test0.js]     at Immediate._tickDomainCallback (internal/process/next_tick.js:122:9)
[test0.js]     at tryOnImmediate (timers.js:554:5)
[test0.js]     at processImmediate [as _immediateCallback] (timers.js:533:5)

[test0.js] Warning: the following test callback was invoked twice by your code for the following test/hook => aaa2

[test0.js] TypeError: "callback" argument must be a function
[test0.js]     at exports.setTimeout (timers.js:322:11)
[test0.js]     at TestSuiteBase.<anonymous> (/Users/t_millal/WebstormProjects/oresoftware/suman/test-target/integration-tests/test0.js:184:13)
[test0.js]     at /Users/t_millal/WebstormProjects/oresoftware/suman/lib/test-suite-helpers/handle-test.js:189:37
[test0.js]     at _combinedTickCallback (internal/process/next_tick.js:67:7)
[test0.js]     at Immediate._tickDomainCallback (internal/process/next_tick.js:122:9)
[test0.js]     at tryOnImmediate (timers.js:554:5)
[test0.js]     at processImmediate [as _immediateCallback] (timers.js:533:5)Warning: the following test callback was invoked twice by your code for the following test/hook => aaa3

[test0.js] TypeError: "callback" argument must be a function
[test0.js]     at exports.setTimeout (timers.js:322:11)
[test0.js]     at TestSuiteBase.<anonymous> (/Users/t_millal/WebstormProjects/oresoftware/suman/test-target/integration-tests/test0.js:160:21)
[test0.js]     at /Users/t_millal/WebstormProjects/oresoftware/suman/lib/test-suite-helpers/handle-test.js:189:37
[test0.js]     at _combinedTickCallback (internal/process/next_tick.js:67:7)
[test0.js]     at process._tickDomainCallback (internal/process/next_tick.js:122:9)Warning: the following test callback was invoked twice by your code for the following test/hook => ddd

[test0.js] 
[test0.js] 
[test0.js]  ### Suman end run ### 
[test0.js] 
[test0.js] 
[test0.js] 
[test0.js] 

[test6.js] 
[test6.js] 
[test6.js]  ### Suman end run ### 
[test6.js] 
[test6.js] 
[test6.js] 
[test6.js] 


### Suman runner end ###








